version: "3.7"

services:
  node:
    build: .
    volumes:
      - .:/rss-node:cached
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 4000:4000
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: node app.js

volumes:
  rss-node:
